### ISSUE TITLE
Issue when generate graphical with vscode

### ISSUE THREAD

**Issue by chems** [ContextMapper/vscode-extension#25]
hi,
First thank you for this extension,
I started with this extension by I m faced this error when trying to genrate garphic (png) 

"The CML Language Server server crashed 5 times in the last 3 minutes. The server will not be restarted."

Thx for your help

**Comment by stefan-ka** [comment]
Hi @chems 
Thanks for reporting this. It was related with the problem that Context Mapper was not yet supporting Java versions newer than 11.
With the release v6.7.0 of today, we support Java 17: https://contextmapper.org/news/2022/12/02/v6.7.0-released/
I think this should solve your problem; if not, feel free to re-open.
Best regards, Stefan
